# Generated by Django 3.2.2 on 2021-05-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tshark_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap_id', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tshark_db_table',
            },
        ),
    ]
