# Generated by Django 3.2.2 on 2021-06-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0003_auto_20210511_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='TsharkLoc1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap_id', models.BigIntegerField(blank=True, null=True)),
                ('tshark_data', models.TextField(blank=True, null=True)),
                ('date', models.CharField(blank=True, db_column='Date', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tshark_loc1',
                'managed': False,
            },
        ),
    ]
