# Generated by Django 3.2.7 on 2021-09-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0004_tsharkloc1'),
    ]

    operations = [
        migrations.CreateModel(
            name='newuserForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=50)),
                ('userid', models.CharField(max_length=20)),
            ],
        ),
    ]
