# Generated by Django 3.2.7 on 2021-09-28 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0005_newuserform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newuserform',
            options={'managed': False},
        ),
    ]
