# Generated by Django 3.2.7 on 2021-09-28 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0006_alter_newuserform_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newuserform',
            table='basicapp_newuserform',
        ),
    ]
