# Generated by Django 3.2.7 on 2021-10-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0009_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
