# Generated by Django 3.2.8 on 2021-10-07 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0010_delete_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_econtact',
            new_name='client_contact',
        ),
    ]
